# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.agent:
    image: wazuh/wazuh-agent:4.14.1
    restart: always
    environment:
      - WAZUH_MANAGER_SERVER=wazuh.manager
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      - wazuh-single-node_default

networks:
  wazuh-single-node_default:
    external: true