services:
  wazuh.agent:
    image: wazuh/wazuh-agent:4.14.1
    restart: always
    environment:
      - WAZUH_MANAGER_SERVER=wazuh.manager
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf
      - ~/.local/etc/Cursor/logs:/host/cursor-logs:ro
    networks:
      - wazuh-single-node_default

networks:
  wazuh-single-node_default:
    external: true